import type { Metadata } from "next";
import "../../../styles/globals.css";

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default async function Layout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <>
    <div className="overflow-x-hidden">
      {children}
    </div>
    </>
  );
}
